Add interactivity to the app
Rahaf91/First-Recap-Project pull request #1
Opened 2024-05-03 06:45 UTC by Rahaf91

2024-05-06 13:46 UTC, eneben requested changes
Ich finde es total schwierig zu beurteilen, was Du alles gemacht hast, ohne die Website angucken zu können. Bei Vercel habe ich leider keinen Zugriff. (Das könntest Du in den Vercel-Einstellungen ändern, glaube ich.) Deshalb konnte ich die Website jetzt nicht testen und einfach mal Eingaben machen und Buttons klicken usw., sondern nur den Code angucken. Ich habe das versucht und denke, der Großteil sieht super aus! Ich habe ein paar kleine Anmerkungen,a ber bin bei vielem, was ich geschrieben habe, selbst nicht sicher. Hätte ich gerne getestet, aber kannst Du ja auch machen. Ich hab jetzt erst mal "Request changes" angeklickt, weil mir halt einiges aufgefallen ist, aber ich finde, im Großen und Ganzen sieht das wirklich schon gut aus. Also falls ich mit meinen Vermutungen unrecht habe, lass es einfach, wie es ist. :sweat_smile: Vielleicht sind für Dich ja sinnvolle Anregungen dabei. Jedenfalls sieht es aus, als wärst Du auf einem ziemlich guten Weg! :rocket:

2024-05-06 13:46 UTC, eneben commented on form.html
> +        <p><b>Your Question</b></p>
ich würde statt <b> eher <strong> verwenden, weil das auch screenreader verstehen. ich glaube, strong ist ein semantisches element und b nur ein visuelles.

2024-05-06 13:46 UTC, eneben commented on js/bookmark.js
> +  const sections = document.querySelectorAll("section");
ich glaube, das brauchst du nicht. ich finde die verschachtelung der for each schleifen ziemlich kompliziert. ich bin nicht sicher, aber vllt könntest du den code auch so schreiben? also ohne die sections und dann mit der definition von links außerhalb der schleife?


```suggestion
  const sections = document.querySelectorAll("section");
```

function BookmarkToggle() {
  const links = document.querySelectorAll("section a.test > i");

  links.forEach((link) => {
    link.addEventListener("click", () => {
      link.classList.toggle("card__icon__bookmarked");
    });
  });
}

2024-05-06 13:46 UTC, eneben commented on js/bookmark.js
> +BookmarkToggle();
ach und ich überlege gerade, dass das doch gar keine funktion sein muss. wenn du einfach den eventlistener hast, brauchst du doch die funktion drumherum nicht und dann auch nicht den call,oder?  ich glaube.

2024-05-06 13:46 UTC, eneben commented on js/form.js
> +  bookmarkIcon.style.fontSize = "48px";
ich würde versuchen den style über css-klassen zu regeln und dann eher eine neue klasse hinzuzufügen. inline-styling ist eher unübersichtlich und teils schwierig, weil es dann eher priorisiert wird und sich schlechter sachen verändern lassen, glaub ich.

2024-05-06 13:46 UTC, eneben commented on js/form.js
> +const maxCharacters = 150;
du könntest auch die maxcharacters definieren als die maxlength von der textarea, damit die rechnung weiter unten auch noch stimmt, wenn du die maxlength anpassen solltest. aber so geht es natürlich auch.

2024-05-06 13:46 UTC, eneben commented on js/form.js
> +form.addEventListener("submit", () => {
das ist quasi der reset, damit wieder angezeigt wird, dass noch 150 zeichen über sind, oder? funktioniert das nicht ohne? ich dachte, wenn du submittest, werden die felder gelöscht, und dann greift vllt der eventlistener oben? schwierig, weil ich die website nicht selbst angucken und dinge ausprobieren kann...

2024-05-06 13:46 UTC, eneben commented on js/index1.js
> +    bookmarkIcon.classList.add("card__icon__bookmarked");
ist das bookmark-icon nicht komplett unabhängig von der angezeigten oder versteckten antwort?

2024-05-06 14:05 UTC, Rahaf91 commented
Danke dir für die Überprüfung. Ich werde deine Kommentare später durchlesen. Du kannst jetzt den Vercel-Link ausprobieren. Ich habe vergessen, die Vercel-Authentifizierung zu ändern.

2024-05-06 14:17 UTC, Rahaf91 commented on js/bookmark.js
> +BookmarkToggle();
Genau, am Anfang habe ich etwas ausprobiert und es sollte eine Funktion haben... aber ja, nicht notwendig.

2024-05-06 14:28 UTC, Rahaf91 commented on js/form.js
> +  bookmarkIcon.style.fontSize = "48px";
Ich habe das Bookmark von Font Awesome mit diesem Inline-Style importiert. Ich habe versucht, es mit CSS-Klassen zu regeln, aber es hat nicht geklappt. Ich schaue später noch einmal nach.

2024-05-06 14:30 UTC, Rahaf91 commented on js/form.js
> +form.addEventListener("submit", () => {
nie habe ich versucht ..

2024-05-06 14:54 UTC, Rahaf91 commented on js/index1.js
> +    bookmarkIcon.classList.add("card__icon__bookmarked");
Ich weiß, dass, wenn wir auf die Button auf der ersten Karte klicken, sich das Bookmark ändern soll , oder? Hierbei beziehe ich mich nur auf die erste Karte, da das Bookmark eine andere Farbe hat.  Auf jeden Fall ich kann das später ändern :)

2024-05-06 19:59 UTC, eneben commented
> Danke dir für die Überprüfung.Du kannst jetzt den Vercel-Link ausprobieren. Ich habe vergessen, die Vercel-Authentifizierung zu ändern.

Ich hab gerade den Vercel-Link angeklickt, danke! Sieht ja super aus, Deine Seite! :-)

2024-05-06 20:07 UTC, eneben commented on js/index1.js
> +    bookmarkIcon.classList.add("card__icon__bookmarked");
Ich denke, es ist so gemeint, dass die Bookmark-Buttons und die Show-/Hide-Answer-Buttons zwei verschiedene Sachen sind, also unabhängig voneinander funktionieren sollten. Bei Deiner Seite funktionieren alle Bookmark-Buttons, aber nur der erste Show-/Hide-Answer-Button. Ich denke, das ist, weil Du bei dem Bookmark-Button weiter oben forEach nimmst und hier nicht. Wir sollten die Funktionalität bis jetzt ja nur für die erste Karte bauen. Falls Du Lust drauf hast, könntest Du ja hier auch probieren, das mit forEach zu lösen. Jedenfalls funktionieren die Bookmarks ja unabhängig von dem Show-/Hide-Answer-Button, also ich denke, hier ist das nicht nötig. :woman_shrugging:

2024-05-06 20:09 UTC, eneben commented on js/form.js
> +  bookmarkIcon.style.fontSize = "48px";
Ist nichts, womit ich mich jetzt ewig aufhalten würde. Klappt ja so alles...

2024-05-06 20:16 UTC, eneben approved these changes

2024-05-06 20:16 UTC, eneben commented on js/index1.js
Ach, was ich noch etwas verwirrend finde, ist, dass Du index.js hast und index1.js. Ist das eine der Darkmode? Dann nenn das doch sonst darkmode.js? Ich glaub, demnächst lernen wir auch noch was zu javascript structure - ich stell mir vor, dass wir da sowas thematisieren.

2024-05-06 20:19 UTC, eneben commented on js/bookmark.js
> +  const sections = document.querySelectorAll("section");
Das hat nicht geklappt, wie es sollte. Ich versuch's noch mal. Bin noch nicht so geübt. 😬

2024-05-07 06:44 UTC, Rahaf91 commented on js/index1.js
Ich habe Dinge ausprobiert und vergessen, die Dateien zu kombinieren.

2024-05-12 14:37 UTC, merged